name: stock_investment_flutter
description: A new Flutter project.

version: 1.0.6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  google_fonts: ^6.2.1
  nb_utils: ^7.0.4
  cached_network_image: ^3.4.1
  fl_chart: ^0.69.0
  url_launcher: ^6.3.0
  palette_generator: ^0.3.3+4
  in_app_update: ^4.2.5
  excel: ^4.0.5
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  iconsax_flutter:
    path: packages/iconsax_flutter
  package_info_plus: ^8.0.2
  shared_preferences: ^2.2.2

  # State Management
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  flutter_riverpod: ^2.5.1

  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.1.0
  firebase_app_check: ^0.3.2+10
  cloud_functions: ^5.0.1
  http: ^1.2.2
  flutter_local_notifications: ^17.2.2
  flutter_image_compress: ^2.3.0
  # Auth + Utils
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  firebase_analytics: ^11.6.0
  webview_flutter: ^4.0.7


dependency_overrides:

  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true
  assets:
    - assets/2.png
    - assets/onboard.png
    - assets/stock/
    - assets/icons/
